#  f=open("Read_file.txt", "r")
f=open(r"C:\Read_file.txt")
# print(f"cursor position- {f.tell()}")
# print(f.read())
# print(f.readline())
# print(f.readline())
lines=f.readlines()
print(lines)
print(len(lines))
for line in lines:
    print(line)
# print(f"cursor position- {f.tell()}")
# f.seek(0)
# print(f"cursor position- {f.tell()}")
# print(f.read())
print(f.name)
print(f.closed)
f.close()
print(f.closed)